package com.app.bzpower.entity;

public class Lockinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lockinfo.id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lockinfo.did
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    private String did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lockinfo.mac
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    private String mac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lockinfo.passcode
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    private String passcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lockinfo.classes
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    private String classes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lockinfo.voltage
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    private String voltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lockinfo.company_id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    private Company companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lockinfo.transformersub_id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    private TransformerSub transformersubId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lockinfo.id
     *
     * @return the value of lockinfo.id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lockinfo.id
     *
     * @param id the value for lockinfo.id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lockinfo.did
     *
     * @return the value of lockinfo.did
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public String getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lockinfo.did
     *
     * @param did the value for lockinfo.did
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lockinfo.mac
     *
     * @return the value of lockinfo.mac
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lockinfo.mac
     *
     * @param mac the value for lockinfo.mac
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lockinfo.passcode
     *
     * @return the value of lockinfo.passcode
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public String getPasscode() {
        return passcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lockinfo.passcode
     *
     * @param passcode the value for lockinfo.passcode
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public void setPasscode(String passcode) {
        this.passcode = passcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lockinfo.classes
     *
     * @return the value of lockinfo.classes
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lockinfo.classes
     *
     * @param classes the value for lockinfo.classes
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public void setClasses(String classes) {
        this.classes = classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lockinfo.voltage
     *
     * @return the value of lockinfo.voltage
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lockinfo.voltage
     *
     * @param voltage the value for lockinfo.voltage
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lockinfo.company_id
     *
     * @return the value of lockinfo.company_id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public Company getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lockinfo.company_id
     *
     * @param companyId the value for lockinfo.company_id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public void setCompanyId(Company companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lockinfo.transformersub_id
     *
     * @return the value of lockinfo.transformersub_id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public TransformerSub getTransformersubId() {
        return transformersubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lockinfo.transformersub_id
     *
     * @param transformersubId the value for lockinfo.transformersub_id
     *
     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
     */
    public void setTransformersubId(TransformerSub transformersubId) {
        this.transformersubId = transformersubId;
    }
}