package com.app.bzpower.entity;

public class TransformerSub {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transformersub.id
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transformersub.transformersub
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    private String transformersub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transformersub.voltage
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    private String voltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transformersub.company_id
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    private Company companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transformersub.id
     *
     * @return the value of transformersub.id
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transformersub.id
     *
     * @param id the value for transformersub.id
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transformersub.transformersub
     *
     * @return the value of transformersub.transformersub
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    public String getTransformersub() {
        return transformersub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transformersub.transformersub
     *
     * @param transformersub the value for transformersub.transformersub
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    public void setTransformersub(String transformersub) {
        this.transformersub = transformersub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transformersub.voltage
     *
     * @return the value of transformersub.voltage
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transformersub.voltage
     *
     * @param voltage the value for transformersub.voltage
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transformersub.company_id
     *
     * @return the value of transformersub.company_id
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    public Company getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transformersub.company_id
     *
     * @param companyId the value for transformersub.company_id
     *
     * @mbg.generated Thu Aug 22 17:18:06 CST 2019
     */
    public void setCompanyId(Company companyId) {
        this.companyId = companyId;
    }
}