package com.app.bzpower.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.app.bzpower.entity.Admin;
import com.app.bzpower.entity.PageData;

public interface AdminMapper {
	Admin adminLogin(Admin example);

	List<Admin> selectByExample(Admin example);

	List<Admin> selectAdminList(@Param("pageData") PageData pageData, @Param("admin") Admin admin);

	Admin selectAdminByUsername(@Param("username")String username);
	
	Admin selectByPrimaryKey(Integer id);

	int updateByPrimaryKeySelective(Admin record);

	int deleteByPrimaryKey(Integer id);

	int countByExample(Admin example);

	int insertSelective(Admin record);
	
	int updatePasswordByUsername(Admin admin);

	/*
	 * List<Admin> selectByExample(Admin example);
	 * 
	 *//**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table admin
		 * 
		 * @mbg.generated Thu Aug 22 17:02:20 CST 2019
		 */
	/*
	 * 
	 * 
	 *//**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table admin
		 * 
		 * @mbg.generated Thu Aug 22 17:02:20 CST 2019
		 */
	/*
	 * int updateByExampleSelective(@Param("record") Admin record, @Param("example")
	 * Admin example);
	 * 
	 *//**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table admin
		 * 
		 * @mbg.generated Thu Aug 22 17:02:20 CST 2019
		 */
	/*
	 * int updateByExample(@Param("record") Admin record, @Param("example") Admin
	 * example);
	 * 
	 *//**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table admin
		 * 
		 * @mbg.generated Thu Aug 22 17:02:20 CST 2019
		 */
	/*
	 * 
	 * 
	 *//**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table admin
		 * 
		 * @mbg.generated Thu Aug 22 17:02:20 CST 2019
		 *//*
			 * int updateByPrimaryKey(Admin record);
			 */

}