package com.app.bzpower.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.app.bzpower.entity.Admin;
import com.app.bzpower.entity.PageData;
import com.app.bzpower.entity.Requestlog;

public interface RequestlogMapper {
	
	
//	List<Requestlog> selectlogList(
//			@Param("requesttime")String requesttime, 
//			@Param("opentime")String opentime, 
//			@Param("phone")String phone);
	
	
	
	List<Requestlog> selectlogList(
			@Param("pageData")PageData pageData,
			@Param("companyname")String companyname, 
			@Param("voltage")String voltage);
	
	
	long countByExample(Admin example);
	
	
	
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    int deleteByExample(Requestlog example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    int insert(Requestlog record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    int insertSelective(Requestlog record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    List<Requestlog> selectByExample(Requestlog example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    Requestlog selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    int updateByExampleSelective(@Param("record") Requestlog record, @Param("example") Requestlog example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    int updateByExample(@Param("record") Requestlog record, @Param("example") Requestlog example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    int updateByPrimaryKeySelective(Requestlog record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table requestlog
//     *
//     * @mbg.generated Thu Aug 22 17:35:27 CST 2019
//     */
//    int updateByPrimaryKey(Requestlog record);
}